// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import dotenv from 'dotenv';
import { defineConfig } from 'prisma/config';
const envFile = `.env.${process.env.NODE_ENV}`;
console.log('envfile', envFile);
dotenv.config({ path: envFile });

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
